# -*- coding: utf-8 -*-
"""RNN

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-wk2sNSz9UmhJpVo5RKRHsphSSbqHogY
"""

class RNN(nn.Module):
    def __init__(
        self,
        vocab_size,
        embedding_dim,
        hidden_dim,
        output_dim,
        n_layers,
        bidirectional,
        dropout_rate,
        pad_index,
    ):
        super().__init__()
        # Q1: Fill this code snippet correctly
        # Hint: You need to call Embedding from torch.nn and pass vocabulary size, the embedding dimension and padding index
        self.embedding = nn.Embedding(vocab_size, embedding_dim, padding_idx=pad_index)#your code here

        # Q2: Fill this code snippet correctly
        # Hint Pass the embedding dim, hidden dim, n layers, bidirection flag, dropout, set batch_first as True
        self.rnn = nn.RNN(
            # your code here
            input_size=embedding_dim,
            hidden_size=hidden_dim,
            num_layers=n_layers,
            bidirectional=bidirectional,
            dropout=dropout_rate,
            batch_first=True
        )

        # Q3: Fill this code snippet correctly
        # Hint: Call the Linear function from Torch.nn where, if bidirectional its is 2*hidden_dim else hidden_dim
        self.fc = nn.Linear(hidden_dim * 2 if bidirectional else hidden_dim, output_dim)# your code here

        self.dropout = nn.Dropout(dropout_rate)

    def forward(self, ids, length):
        # Q4: Fill this code snippet correctly
        embedded = self.dropout(self.embedding(ids))
        # Hint: Use pack_padded_sequence from torch.nn.utils.rnn and pass  embedded, length, batch_first=True, enforce_sorted=False
        packed_embedded = nn.utils.rnn.pack_padded_sequence(embedded, length, batch_first=True, enforce_sorted=False)# your code here
        packed_output, hidden = self.rnn(packed_embedded)
        output, output_length = nn.utils.rnn.pad_packed_sequence(packed_output)

        # Q5: Fill this code snippet correctly
        if self.rnn.bidirectional:
            # Concatenate hidden[-1], hidden[-2] along dim -1 (make sure to use dropout as well)
            hidden = self.dropout(torch.cat((hidden[-2], hidden[-1]), dim=1))# your code here
        else:
            # Use hidden[-1] (make sure to use dropout as well)
            hidden = self.dropout(hidden[-1]) # your code here

        prediction = self.fc(hidden)
        return prediction